[[redirects]]
  from = "/newsapi"
  to = "http://newsapi.org/v2/everything"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/omdbapi"
  to = "http://www.omdbapi.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[redirects]]
  from = "/*"
  to = "404"
  status = 404